/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as KemitraanRouteImport } from './routes/kemitraan'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as LokasiRouteImport } from './routes/lokasi'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalitikRouteImport } from './routes/admin.analitik'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminInventoriRouteImport } from './routes/admin.inventori'
import { Route as AdminInvoiceRouteImport } from './routes/admin.invoice'
import { Route as AdminKasirRouteImport } from './routes/admin.kasir'
import { Route as AdminKeuanganRouteImport } from './routes/admin.keuangan'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminNotifikasiRouteImport } from './routes/admin.notifikasi'
import { Route as AdminPelangganRouteImport } from './routes/admin.pelanggan'
import { Route as AdminPengaturanRouteImport } from './routes/admin.pengaturan'
import { Route as AdminPesananRouteImport } from './routes/admin.pesanan'
import { Route as AdminPromoRouteImport } from './routes/admin.promo'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminVoucherRouteImport } from './routes/admin.voucher'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as MenuSlugRouteImport } from './routes/menu.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KemitraanRoute = KemitraanRouteImport.update({
  id: '/kemitraan',
  path: '/kemitraan',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const LokasiRoute = LokasiRouteImport.update({
  id: '/lokasi',
  path: '/lokasi',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalitikRoute = AdminAnalitikRouteImport.update({
  id: '/analitik',
  path: '/analitik',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoriRoute = AdminInventoriRouteImport.update({
  id: '/inventori',
  path: '/inventori',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoiceRoute = AdminInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKasirRoute = AdminKasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeuanganRoute = AdminKeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotifikasiRoute = AdminNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPelangganRoute = AdminPelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPesananRoute = AdminPesananRouteImport.update({
  id: '/pesanan',
  path: '/pesanan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromoRoute = AdminPromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVoucherRoute = AdminVoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => AdminRoute,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuSlugRoute = MenuSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MenuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kemitraan': typeof KemitraanRoute
  '/kontak': typeof KontakRoute
  '/lokasi': typeof LokasiRoute
  '/menu': typeof MenuRouteWithChildren
  '/promo': typeof PromoRoute
  '/tentang': typeof TentangRoute
  '/admin/analitik': typeof AdminAnalitikRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/inventori': typeof AdminInventoriRoute
  '/admin/invoice': typeof AdminInvoiceRoute
  '/admin/kasir': typeof AdminKasirRoute
  '/admin/keuangan': typeof AdminKeuanganRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pelanggan': typeof AdminPelangganRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pesanan': typeof AdminPesananRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/voucher': typeof AdminVoucherRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/menu/': typeof MenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kemitraan': typeof KemitraanRoute
  '/kontak': typeof KontakRoute
  '/lokasi': typeof LokasiRoute
  '/promo': typeof PromoRoute
  '/tentang': typeof TentangRoute
  '/admin/analitik': typeof AdminAnalitikRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/inventori': typeof AdminInventoriRoute
  '/admin/invoice': typeof AdminInvoiceRoute
  '/admin/kasir': typeof AdminKasirRoute
  '/admin/keuangan': typeof AdminKeuanganRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pelanggan': typeof AdminPelangganRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pesanan': typeof AdminPesananRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/voucher': typeof AdminVoucherRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/admin': typeof AdminIndexRoute
  '/menu': typeof MenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kemitraan': typeof KemitraanRoute
  '/kontak': typeof KontakRoute
  '/lokasi': typeof LokasiRoute
  '/menu': typeof MenuRouteWithChildren
  '/promo': typeof PromoRoute
  '/tentang': typeof TentangRoute
  '/admin/analitik': typeof AdminAnalitikRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/inventori': typeof AdminInventoriRoute
  '/admin/invoice': typeof AdminInvoiceRoute
  '/admin/kasir': typeof AdminKasirRoute
  '/admin/keuangan': typeof AdminKeuanganRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pelanggan': typeof AdminPelangganRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pesanan': typeof AdminPesananRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/voucher': typeof AdminVoucherRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/menu/': typeof MenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kemitraan'
    | '/kontak'
    | '/lokasi'
    | '/menu'
    | '/promo'
    | '/tentang'
    | '/admin/analitik'
    | '/admin/inbox'
    | '/admin/inventori'
    | '/admin/invoice'
    | '/admin/kasir'
    | '/admin/keuangan'
    | '/admin/menu'
    | '/admin/notifikasi'
    | '/admin/pelanggan'
    | '/admin/pengaturan'
    | '/admin/pesanan'
    | '/admin/promo'
    | '/admin/review'
    | '/admin/voucher'
    | '/menu/$slug'
    | '/admin/'
    | '/menu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kemitraan'
    | '/kontak'
    | '/lokasi'
    | '/promo'
    | '/tentang'
    | '/admin/analitik'
    | '/admin/inbox'
    | '/admin/inventori'
    | '/admin/invoice'
    | '/admin/kasir'
    | '/admin/keuangan'
    | '/admin/menu'
    | '/admin/notifikasi'
    | '/admin/pelanggan'
    | '/admin/pengaturan'
    | '/admin/pesanan'
    | '/admin/promo'
    | '/admin/review'
    | '/admin/voucher'
    | '/menu/$slug'
    | '/admin'
    | '/menu'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kemitraan'
    | '/kontak'
    | '/lokasi'
    | '/menu'
    | '/promo'
    | '/tentang'
    | '/admin/analitik'
    | '/admin/inbox'
    | '/admin/inventori'
    | '/admin/invoice'
    | '/admin/kasir'
    | '/admin/keuangan'
    | '/admin/menu'
    | '/admin/notifikasi'
    | '/admin/pelanggan'
    | '/admin/pengaturan'
    | '/admin/pesanan'
    | '/admin/promo'
    | '/admin/review'
    | '/admin/voucher'
    | '/menu/$slug'
    | '/admin/'
    | '/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  KemitraanRoute: typeof KemitraanRoute
  KontakRoute: typeof KontakRoute
  LokasiRoute: typeof LokasiRoute
  MenuRoute: typeof MenuRouteWithChildren
  PromoRoute: typeof PromoRoute
  TentangRoute: typeof TentangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kemitraan': {
      id: '/kemitraan'
      path: '/kemitraan'
      fullPath: '/kemitraan'
      preLoaderRoute: typeof KemitraanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lokasi': {
      id: '/lokasi'
      path: '/lokasi'
      fullPath: '/lokasi'
      preLoaderRoute: typeof LokasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analitik': {
      id: '/admin/analitik'
      path: '/analitik'
      fullPath: '/admin/analitik'
      preLoaderRoute: typeof AdminAnalitikRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventori': {
      id: '/admin/inventori'
      path: '/inventori'
      fullPath: '/admin/inventori'
      preLoaderRoute: typeof AdminInventoriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoice': {
      id: '/admin/invoice'
      path: '/invoice'
      fullPath: '/admin/invoice'
      preLoaderRoute: typeof AdminInvoiceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kasir': {
      id: '/admin/kasir'
      path: '/kasir'
      fullPath: '/admin/kasir'
      preLoaderRoute: typeof AdminKasirRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/keuangan': {
      id: '/admin/keuangan'
      path: '/keuangan'
      fullPath: '/admin/keuangan'
      preLoaderRoute: typeof AdminKeuanganRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifikasi': {
      id: '/admin/notifikasi'
      path: '/notifikasi'
      fullPath: '/admin/notifikasi'
      preLoaderRoute: typeof AdminNotifikasiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pelanggan': {
      id: '/admin/pelanggan'
      path: '/pelanggan'
      fullPath: '/admin/pelanggan'
      preLoaderRoute: typeof AdminPelangganRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pesanan': {
      id: '/admin/pesanan'
      path: '/pesanan'
      fullPath: '/admin/pesanan'
      preLoaderRoute: typeof AdminPesananRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promo': {
      id: '/admin/promo'
      path: '/promo'
      fullPath: '/admin/promo'
      preLoaderRoute: typeof AdminPromoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/voucher': {
      id: '/admin/voucher'
      path: '/voucher'
      fullPath: '/admin/voucher'
      preLoaderRoute: typeof AdminVoucherRouteImport
      parentRoute: typeof AdminRoute
    }
    '/menu/': {
      id: '/menu/'
      path: '/'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/$slug': {
      id: '/menu/$slug'
      path: '/$slug'
      fullPath: '/menu/$slug'
      preLoaderRoute: typeof MenuSlugRouteImport
      parentRoute: typeof MenuRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalitikRoute: typeof AdminAnalitikRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminInventoriRoute: typeof AdminInventoriRoute
  AdminInvoiceRoute: typeof AdminInvoiceRoute
  AdminKasirRoute: typeof AdminKasirRoute
  AdminKeuanganRoute: typeof AdminKeuanganRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminNotifikasiRoute: typeof AdminNotifikasiRoute
  AdminPelangganRoute: typeof AdminPelangganRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminPesananRoute: typeof AdminPesananRoute
  AdminPromoRoute: typeof AdminPromoRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminVoucherRoute: typeof AdminVoucherRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalitikRoute: AdminAnalitikRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminInventoriRoute: AdminInventoriRoute,
  AdminInvoiceRoute: AdminInvoiceRoute,
  AdminKasirRoute: AdminKasirRoute,
  AdminKeuanganRoute: AdminKeuanganRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminNotifikasiRoute: AdminNotifikasiRoute,
  AdminPelangganRoute: AdminPelangganRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminPesananRoute: AdminPesananRoute,
  AdminPromoRoute: AdminPromoRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminVoucherRoute: AdminVoucherRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MenuRouteChildren {
  MenuSlugRoute: typeof MenuSlugRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuSlugRoute: MenuSlugRoute,
  MenuIndexRoute: MenuIndexRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  KemitraanRoute: KemitraanRoute,
  KontakRoute: KontakRoute,
  LokasiRoute: LokasiRoute,
  MenuRoute: MenuRouteWithChildren,
  PromoRoute: PromoRoute,
  TentangRoute: TentangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
